export const LOGIN_STARTED = "LOGIN_STARTED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const LOGOUT = "LOGOUT";

export const SET_USER_STATE = "SET_USER_STATE";

export const ACTIVATION_STARTED = "ACTIVATION_STARTED";
export const ACTIVATION_SUCCESS = "ACTIVATION_SUCCESS";
export const ACTIVATION_ERROR = "ACTIVATION_ERROR";

export const REGISTRATION_STARTED = "REGISTRATION_STARTED";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";

export const CREATING_POST_STARTED = "CREATING_POST_STARTED";
export const CREATING_POST_SUCCESS = "CREATING_POST_SUCCESS";
export const CREATING_POST_ERROR = "CREATING_POST_ERROR";
