export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const REGISTRATION_STARTED = "REGISTRATION_STARTED";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const REGISTRATION_ERROR = "REGISTRATION_ERROR";
